services:
  - type: web
    name: fitstack-api
    runtime: docker
    repo: https://github.com/jprocode/FitStack
    branch: main
    rootDir: fitness-platform-backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: USER_DATABASE_URL
        sync: false
      - key: WORKOUT_DATABASE_URL
        sync: false
      - key: NUTRITION_DATABASE_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: USDA_API_KEY
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: EXERCISE_API_KEY
        sync: false
      - key: PORT
        value: "8080"
    healthCheckPath: /actuator/health
